# No more WakaRuntime Failed again!
# name: Waka Readme

# on:
#   schedule:
#     # Runs at 0:00
#     - cron: '0 0 * * *'
#   workflow_dispatch:
# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           SYMBOL_VERSION: 3
#           SHOW_OS: "False"
#           SHOW_PROFILE_VIEWS: "False"
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

